### ISSUE TITLE
Would this work on Alteryx Gallery as well?

### ISSUE THREAD

**Issue by niravparikh** [bobpeers/Alteryx_SDK_Snowflake_Output#1]
Hi Bob, thanks for writing the python snowflake connector, eager to try this out. Quick question , would this work on Alteryx Gallery? or it would run into the same javascript password encrypt , python password decrypt issue that we run into with other tools with html front end and python back end.  Would love to hear from you.

**Comment by bobpeers** [comment]
Duplicate of #2
